# -*- coding: utf-8 -*-
"""README の「本文で報告する量 → 結果ファイル → 生成スクリプト」対応表を作る。

原稿からリポジトリ内パスを外した代わりに、この表が対応を持つ（Data Availability が約束）。
量とファイルの対応は verify_numbers.py --map の出力をそのまま使い、
生成スクリプトはファイル名がどのスクリプトに書き出しとして現れるかで決める。
"""
from __future__ import annotations
import pathlib
import re
import sys

import pandas as pd

HERE = pathlib.Path(__file__).resolve().parents[2]
MAP = HERE / "results" / "round9" / "quantity_to_file.tsv"
OUT = HERE / "results" / "round9"

SKIP = ("verify_numbers.py", "make_figures.py", "build_readme_map.py")
WRITE = re.compile(r"to_csv|write_text|savefig|to_markdown")


def producers() -> dict[str, str]:
    """results/provenance.tsv を正本として、結果ファイル → 生成スクリプトを返す。

    生成元の判定は build_provenance.py が持つ。ここで二重に実装しない。
    """
    pv = HERE / "results" / "provenance.tsv"
    if not pv.exists():
        raise SystemExit("先に `python code/revision1/build_provenance.py` を実行すること")
    d = pd.read_csv(pv, sep="\t").fillna({"producer": ""})
    out = {}
    for r in d.itertuples():
        rel = str(r.result_file)[len("results/"):] if str(r.result_file).startswith("results/") \
            else str(r.result_file)
        out[rel] = str(r.producer)
    return out


def main() -> int:
    if not MAP.exists():
        print("先に `python verify_numbers.py --map` を実行すること", file=sys.stderr)
        return 1
    d = pd.read_csv(MAP, sep="\t")
    prod = producers()
    d["script"] = [prod.get(f, "") for f in d.result_file]
    # 生成スクリプトが repo に無いファイルは、そうと分かるように書く。黙って空欄にしない。
    d["script"] = d["script"].replace("", "not regenerated by a script in this repository")

    # ファイル単位に畳む。README で読むのはこちら。
    g = (d.groupby(["result_file", "script"], dropna=False)["quantity"]
           .apply(lambda s: "; ".join(s)).reset_index())
    g["n_quantities"] = [len(q.split("; ")) for q in g.quantity]
    g = g.sort_values("result_file")
    g.to_csv(OUT / "readme_file_map.tsv", sep="\t", index=False)

    lines = ["| Result file | Produced by | Quantities it supplies |", "|---|---|---|"]
    for r in g.itertuples():
        lines.append(f"| `projection/results/{r.result_file}` | "
                     f"{('`' + r.script + '`') if r.script else '—'} | {r.quantity} |")
    (OUT / "readme_file_map.md").write_text("\n".join(lines) + "\n")
    print(f"{len(g)} ファイル / {len(d)} 量 → {OUT/'readme_file_map.md'}")
    miss = g[g.script.str.startswith("not regenerated")]
    if len(miss):
        print("生成スクリプトが特定できなかったファイル:", list(miss.result_file))
    return 0


if __name__ == "__main__":
    sys.exit(main())
